name: Branch check
on: pull_request:
    branches:
      - '*'
jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - name: Check branch
      run: |
        import os
        import re
        import subprocess

        def version() :

          versions = {}
          versionRe = re.compile( r"^(gaffer.*Version.*) = (\S+)" )
          with open( "SConstruct" ) as sconstruct :
            for line in sconstruct.readlines() :
              versionMatch = versionRe.match( line )
              if versionMatch :
                versions[versionMatch.group( 1 )] = versionMatch.group( 2 ).strip( "'\"" )

          return [ int( versions["gafferMilestoneVersion"] ), int( versions["gafferMajorVersion"] ) ]

        currentVersion = version()
        print( currentVersion )

        targetBranch = os.environ["GITHUB_BASE_REF"]
        subprocess.check_call( [ "git", "checkout", targetBranch ] )
        targetVersion = version()

        if targetVersion != currentVersion :
          sys.stderr.write(
            "Current version {} does not match target branch version {}\n".format(
              currentVersion, targetVersion
            )
          )
          sys.exit( 1 )

        print( os.environ )

      shell: python
