name: CI

on:
  push:
    branches:
      - main
      - '*'
  pull_request:
    branches:
      - main
      - '*_maintenance'
  release:
      types: [published]

jobs:

  build:

    strategy:

      # Don't cancel other jobs in the build matrix if one job fails.
      fail-fast: false

      matrix:

        # Rather than generate all permutations of various settings,
        # we want to explicitly list each of the variants we want to
        # test. We can use `name` to declare the names of our variants,
        # and then use `include` to define their settings.

        name: [
          linux-python2,
          linux-python2-debug,
          linux-python3,
          macos-python2,
        ]

        include:

          - name: linux-python2
            os: ubuntu-20.04
            buildType: RELEASE
            publish: true
            containerImage: ghcr.io/gafferhq/build/build:1.2.0
            dependenciesURL: https://github.com/GafferHQ/dependencies/releases/download/4.0.0/gafferDependencies-4.0.0-Python2-linux.tar.gz
            # GitHub container builds run as root. This causes failures for tests that
            # assert that filesystem permissions are respected, because root doesn't
            # respect permissions. So we run the final test suite as a dedicated
            # test user rather than as root.
            testRunner: su testUser -c
            sconsCacheMegabytes: 400

          - name: linux-python2-debug
            os: ubuntu-20.04
            buildType: DEBUG
            publish: false
            containerImage: ghcr.io/gafferhq/build/build:1.2.0
            dependenciesURL: https://github.com/GafferHQ/dependencies/releases/download/4.0.0/gafferDependencies-4.0.0-Python2-linux.tar.gz
            testRunner: su testUser -c
            # Debug builds are ludicrously big, so we must use a larger cache
            # limit. In practice this compresses down to 4-500Mb.
            sconsCacheMegabytes: 2500

          - name: linux-python3
            os: ubuntu-20.04
            buildType: RELEASE
            publish: true
            containerImage: ghcr.io/gafferhq/build/build:1.2.0
            dependenciesURL: https://github.com/GafferHQ/dependencies/releases/download/4.0.0/gafferDependencies-4.0.0-Python3-linux.tar.gz
            testRunner: su testUser -c
            sconsCacheMegabytes: 400

          - name: macos-python2
            os: macos-10.15
            buildType: RELEASE
            publish: true
            containerImage:
            dependenciesURL: https://github.com/GafferHQ/dependencies/releases/download/4.0.0/gafferDependencies-4.0.0-Python2-osx.tar.gz
            testRunner: bash -c
            sconsCacheMegabytes: 400

    runs-on: ${{ matrix.os }}

    container: ${{ matrix.containerImage }}

    env:
      DISPLAY: ":99.0"
      ARNOLD_LICENSE_ORDER: none # Don't waste time looking for a license that doesn't exist
      GAFFER_BUILD_DIR: "./build"
      GAFFER_CACHE_DIR: "./sconsCache"

    steps:

    - uses: actions/checkout@v2

    - name: Install toolchain (MacOS)
      run: |
        python --version
